project:
  type: website
  output-dir: docs
  resources: 
    - assets/**


website:
  title: "Sugar Kelp LD Atlas"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: functions.qmd
        text: Browse by function
      - href: acknowledgements.qmd  
        text: Acknowledgements
        

format:
  html:
    theme: cosmo
    toc: true
    toc-location: left
    page-layout: full

execute:
  freeze: false