project:
  type: website
  output-dir: docs
  resources: 
    -assets/**
  
resources: 
  - assets

website:
  title: "Sugar Kelp LD Atlas"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: functions.qmd
        text: Browse by function

format:
  html:
    theme: cosmo
    toc: true
    toc-location: left

execute:
  freeze: auto